### ISSUE TITLE
Website backup and checklist for PHP upgrade

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#178]
Our Wordpress blog server will be upgraded to PHP 8.0 shortly, so we are to do the following steps to prepare:

- [x] Create a backup of your website.
- [ ] Make sure you have the latest version of WordPress. 
- [ ] Double-check your plugins and themes are compatible with PHP 8.0.

**Comment by smlambert** [comment]
I created a backup of our website today (1st of the 3 tasks outlined in the description).
