### ISSUE TITLE
Farm-wide Walking Path (TD FEF) Timeline

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#211]
**Phase 1: FCF Pathway**
| Timing | Activity &#9744; &#9745;| Owner | Status |
| --- | --- | --- | --- |
- [x] Complete template for signage. Signage across pathway and across organizations will have the same format
- [x] Design route of pathway and create a digital map
- [x] Consult other organizations at Just Food regarding possible designs of the pathway. Final submission of signage content for each activity
- [x] procurement of materials for walking path including but not limited to ~~wood chips~~**, gravel, grass, seed, signage
- [ ] Procurement of educational materials including but not limited to pamphlets and posters.
- [x] Construct a walking path through 9 acre plots of FCF as a pilot
- [ ] Report on lessons learned from the pilot and use results towards the completion of the second phase

**Phase 2: Farm-wide Pathway**
| Timing | Activity &#9744; &#9745;| Owner | Status |
| --- | --- | --- | --- |
- [ ] Procurement of materials for signage
- [ ] Awareness campaign to engage local community groups and gain public interest in the project
- [ ] Support from FCF, Just Food and community volunteers to build pathways
- [ ] Measure and report on KPIs
- [ ] Ongoing maintenance of pathway and signage
- [ ] Ongoing maintenance of foraging shrubs and trees. Maintenance of shrubs and trees will follow the afforestation framework by FCF
- [ ] Community engagement and awareness campaign for the event
- [ ] Plan event

[TD FEF Proposal Workplan](https://docs.google.com/spreadsheets/d/1pNcc57sRPg6vJ5Me5kJuxEsAi0AWLgrk_aWqvBiYVeM/edit?usp=sharing)
[TD FEF Budget](https://docs.google.com/spreadsheets/d/1A6_BmkapIFvnqCZtXV7QgUpNBOYcolIb/edit?usp=sharing&ouid=104658172105924753645&rtpof=true&sd=true)

**  striking out wood chips as we explicitly will not be using them for pathways, they deteriorate quickly (so would need to be redone every other year) and cause issues when trying to mow the path (schrapnel flying, unsafe and unpleasant), they are used for mulch around trees, so we may train/encourage people into thinking it is acceptable to walk on woodchips which is a behaviour we do not want.

**Comment by MartinNesbitt** [comment]
[Timeline for creating the signage template and website domain](https://docs.google.com/document/d/1Miwh9xsT_PHtVKBx-lwnB3sRQll8YsNG0n0kYtFBTus/edit?usp=sharing)

**Comment by smlambert** [comment]
Shall we update the dates within the document shared in https://github.com/ForetCapitaleForest/actions/issues/211#issuecomment-1428344696, to reflect the new timeline?

I have added some notes at the bottom, regarding domain (not for public sharing at this time).

**Comment by MartinNesbitt** [comment]
$1428 funds remain for project management and website/arcgis/educational materials development.
