### ISSUE TITLE
EPIC: NCC Hogs Back contract 2022

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#27]
- [x] Insurance certificates @StephMcNeely; 

- [x] contract amendments (invoicing for trees), 

- [x] Obtain NCC approval for tree species and/or planting plan (OK - done by email)

- [x] Apply for Special Event Authorization 

- [x] #28

- [ ] #29
- [x] Prepare FCF invoice for tree order ASAP @StephMcNeely 
- [x] #38

**Comment by smlambert** [comment]
One last thing for this issue to be completed is the 365 report https://github.com/ForetCapitaleForest/actions/issues/29 which is due this month.

**Comment by smlambert** [comment]
Going to close this now.
