### ISSUE TITLE
EPIC: New Greenhouse Build Project Plan

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#366]
A project plan for building the FCF Greenhouse

- [x] Remove Pine Tree https://github.com/ForetCapitaleForest/actions/issues/306
- [x] Remove two large mounds:  large mound of soil that has recently been mowed and a mound of compostable material.
- [x] Mow all the long grass and shrubs where the greenhouse will go
- [x] Women Warriors to Place their shed
- [x] Ensure water line is dug and installed (trenching work)
- [x] Procure gravel
- [x] Place and flatten gravel #322 
- [x] #367
- [x] #400
- [x] #508

**Comment by jodinewman** [comment]
Greenhouse is DONE. Nobody is allowed to mention the building process to me ever again, thanks!!

**Comment by StephMcNeely** [comment]
Noted Jodi ;)
