### ISSUE TITLE
EPIC: TD FEF 2023 Grant Workplan

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#423]
Work Dedicated to completing the TD FEF Grant. [Folder](https://drive.google.com/drive/folders/10jJRhe2Qa5SxTZM6BxHyTgFVQ20Hzb5o?usp=sharing) of all the relevant grant files including application outlining deliverables and anticipated outcomes, budget, etc. 

[Link](https://docs.google.com/spreadsheets/d/1pNcc57sRPg6vJ5Me5kJuxEsAi0AWLgrk_aWqvBiYVeM/edit?usp=sharing) to excel workplan and general notes 

**Admin**
- [x] Create expense tracking sheet/working budget

**Procurement of signage materials** 
- [x] Finalize signage descriptions 
- [x] Finalize signage diagrams  
- [x] Finalize signage designs  
- [x] Create Temporary Signage for the summer ***must recoginize TD for their support  

**Build sign posts** 
- [ ] Dig sign post holes 
- [x] Double check sign post procurement list  
- [x] Procure any needed sign post equipment  
- [ ] Place and set sign posts in the ground (using grave & quickcrete mix) 

**Community Engagement** 
- [ ] Social media posts during construction   
- [x] Provide info in the newsletters  

**Plan Celebratory Event**   
- [x] Set the date for the event and let TD know many weeks in advance  
- [x] Begin to plan theme for the event   
- [x] Social media content leading up to the event 

**Evaluation and Maintenance**   
- [x] Create spreadsheet and ghant chart as a tool to measure our progress on walking path  
- [ ] Create survey to track progress on qualitative outcomes   
- [ ] Create/update virtual interactive tour   
- [x] Begin writing notes and drafting the final report
