### ISSUE TITLE
EPIC: Update website

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#497]
- [x] Update team members on Our Team page - still need to add Matthew
- [x] add https://www.youtube.com/watch?v=dBBZ361lUpo to the Resources page
- [x] https://github.com/ForetCapitaleForest/actions/issues/26
- [x] https://github.com/ForetCapitaleForest/actions/issues/462
- [x] #515
- [x] #550
- [x] #549

**Comment by smlambert** [comment]
Team page updated, but 2 new photos are not cropped in the same way as the other photos, not sure who did the other photos (cropped in a circle shape), but we should try to match the new ones up.

**Comment by smlambert** [comment]
Still need to add @Matthewtennant to the Team page, @jodinewman to assist

**Comment by ShellCrabtree** [comment]
NOTE: Add other organizations to the site only if they link back to our collateral.
