### ISSUE TITLE
RD: August Site Visit

### ISSUE THREAD

**Issue by Matthewtennant** [ForetCapitaleForest/actions#665]
### Site Name: Parc Rapides-DesChênes / Rue Scott & Graham
**Site Address:**
### Materials Needed
- [ ] String Trimmer
- [ ] Camera
- [ ] Water Pump
- [ ] Spare Dewalt Batteries
- [ ] Notebook
- [ ] Gloves
- [ ] Garbage Bags (for invasive species)
### Tasks
- [ ] Water all trees on site (if necessary)
- [ ] Fill water totes from river (at Parc R-D) or schedule water delivery if needed (Rue Scott & Graham)
- [ ] Remove competing vegetation from around base of trees by hand, followed by string trimming within fence perimeter
- [ ] Check fencing for tampering/holes, fix if found
- [ ] Conduct visual inspection of trees for damage, death or disease. Treat if urgent or make note if not for 365 report

**Comment by smlambert** [comment]
August is in the past, is this completed?
