### ISSUE TITLE
BoO site closure list of To Dos

### ISSUE THREAD

**Issue by ShellCrabtree** [ForetCapitaleForest/actions#774]
Document prepared by Colleen and Shelley L. [Winterizing the Base of Operations ](https://docs.google.com/document/d/1oKdxJn1riP-6UOibd-F5o87NxBEDD55LlZvvtfRY6po/edit)

- [x] Separate trees based on their planting 
- [x] Check plantings, may have to replant in mound to raise the bushes up

**Tasks that can be done now for winterizing** 

- [x] Clean Water totes / Make sure there is nothing in them that will freeze and damage the spouts 
- [x] Make sure that water tote spouts are left open 
- [x] Finish putting on Tree Guards [Can be done with volunteers] 
    - Prioritize actual trees like apple, don’t need to put tree guards on shrubs (ex service berry & elder berry)
- [x] Roll up irrigation that isn’t used 
- [x] Check if plastic sheets / frost blankets are in stock for covering plants if not see about ordering (need to check with Jodi) Will use up burlap first and see how much is left to be covered 
- [x] Whippersnipp around fruit trees (optional if out of time) - can happen after freeze  
- [x] Apply Bobbex on trees - can happen after freeze 
- [x] Fix fencing around tiny forest - do ASAP - will need bamboo sticks min 4 fence down in 3 places , clippers to cut grass, string or twine, mallet, [Can be done with volunteers] 
- [x] Stack empty pots neatly 
- [x] Move Plastic Shed - can wait till November 
- [x] See about pulling up landscape fabric & store for winter at least at - will no be doing this season
- [x] Clean/organize FCF Greenhouse 
- [ ] Build potting benches 
- [x] Gravel to be moved to field 3 at exist near Hügelkultur

**Tasks when plantings are completed (after October 28 final plantings)**  

- [x] Final inventory of tools at base
- [x] Putting the trees down for the winter for overwintering. Photo of process attached. Inventory spreadsheet link: https://docs.google.com/spreadsheets/d/1kvga3rdcazG_BpShq84pjvPkEXs6EtkBcuS7MAl06i4/edit?usp=drivesdk [Can be done with volunteers]
- [x] Final inventory of trees that will be overwintering at the base 
- [x] Sort Baker pots to go back - ID how many need to be shipped and when so we can contact shipping
- [x] Drain water from hoses [Can be done with volunteers, LB is checking with her dad re: air compressor]
- [x] Shelley L to take batteries & other freezables

**Comment by smlambert** [comment]
> Gravel to be moved to field 3 at exist near Hügelkultur

To clarify, this is not to move gravel into the field, but to create a ditch crossing into the field.  In fact, there are 2 locations for 2 new 'crossings' (one into field 3 where the long hugel is on the right as you enter the field, and two at field 4 just past the tiny forest demonstration plots and where one of the new signs is placed).  They will not need to be like our other ditch crossings, as they are in locations where the ditch is 'shallower'.

I had understood we had some extra 4" diameter pipe that could be laid down along with some gravel, so water does not dam up on either side of the new crossings.  

This will not use up all of the extra gravel, but once we move the plastic shed, some of the extra gravel can be used to level the area in front of greenhouses and around the water pump.  We can also then allocated parking areas to ensure that there are still 2 parking spots reserved for Nanabush, 1 swing spot for Sundaura and 2 spots to the right of the wooden shed for FCF.  Then we can also ensure that the 'non-FCF' parking does not get blocked by FCF "stuff", including tipped over trees, EV trailers and contents, traffic cones, etc.  Let's try to think of the site as a neighbourhood and try to avoid blocking the neighbours driveways.

**Comment by jodinewman** [comment]
![1000014503](https://github.com/user-attachments/assets/e1b7acb1-a92d-4b3e-be84-a9e4eca72fd2)
